version: '3.9'

services:
  web:
    container_name: stackcode_web_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - DATABASE_URL=mysql://stackcode:stackcode@mariadb:3306/stackcode
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mariadb
      - redis



  mariadb:
    image: mariadb:11
    container_name: stackcode_mariadb_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stackcode
      MYSQL_USER: stackcode
      MYSQL_PASSWORD: stackcode
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stackcode_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: stackcode
      PMA_PASSWORD: stackcode
    depends_on:
      - mariadb


volumes:
  mariadb_data:
